"""remove_whatsapp_columns

Revision ID: bbc2e03eb5e1
Revises: 0001
Create Date: 2026-02-03 05:35:51.137879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc2e03eb5e1'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index(op.f('ix_users_whatsapp'), table_name='users')
    op.drop_index(op.f('ix_users_whatsapp_number'), table_name='users')
    op.drop_column('users', 'is_whatsapp_verified')
    op.drop_column('users', 'whatsapp_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whatsapp_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_whatsapp_verified', sa.BOOLEAN(), autoincrement=False, nullable=True, server_default='false'))
    # Update existing rows to have a default value
    op.execute("UPDATE users SET is_whatsapp_verified = false WHERE is_whatsapp_verified IS NULL")
    # Now make the column NOT NULL
    op.alter_column('users', 'is_whatsapp_verified', nullable=False)
    op.create_index(op.f('ix_users_whatsapp_number'), 'users', ['whatsapp_number'], unique=True)
    op.create_index(op.f('ix_users_whatsapp'), 'users', ['whatsapp_number'], unique=False)
    op.alter_column('users', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
