from routes.languages import router as languages_router
from routes.genres import router as genres_router
from routes.authors import router as authors_router
from routes.artists import router as artists_router
from routes.publications import router as publications_router
from routes.books import router as books_router
from routes.files import router as files_router
from routes.auth import router as auth_router
from routes.user_auth import router as user_auth_router
from routes.search import router as search_router
from routes.user_activity import router as user_activity_router
